version: '3.8'

services:
   mysqldb:
    container_name: mysqlcontainer
    image: mysql:latest
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: "root"
       MYSQL_DATABASE: "publications"
       MYSQL_USER: "admin"
       MYSQL_PASSWORD: "root"
       MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
       #MYSQL_RANDOM_ROOT_PASSWORD: "none"
       
     
    volumes:
      - db:/var/lib/mysql
    # networks: 
    #   - publication  
   app:
    container_name: publicationcontainer
    tty: true
    depends_on:
      - mysqldb
    image: node:latest  
    build: .
    restart: always 
    ports:
      - 5000:5000
    expose:
      - 5000  
    environment:
        DB_HOST: 'mysqldb'
        DB_USER: 'admin'
        DB_PASSWORD: 'root'
        DB_NAME: 'publications'
        DB_PORT: 3306
    # networks:
    #   - publication
volumes: 
  db: